Qbox-project/txAdminRecipe

qbcore.yaml
server.cfg

Added ox to the recipe *This will support all future ox updates*
#3 Didnt need to add anything to the server.cfg since it was done here

OX download Support Added

---

server.cfg

Added Ox target convar support (copy and paste of snippet from docs)

Ox Target Convars

---

qbox.sql

unnecessary tables

---

ox.cfg

target changes source : https://discord.com/channels/813030955598086174/878287993620799498/1041119771162312764
target click button config

adapt latest target changes from ox & feat: target click config on ox.cfg

---

ox.cfg

https://github.com/overextended/ox_lib/releases/tag/v3.0.0#:~:text=Added%20ox%3AprimaryColor%20and%20ox%3AprimaryShade%20convars%2C%20which%20allow%20you%20to%20easily%20change%20the%20primary%20colour%20of%20the%20UI%20(progress%20bar/circle%2C%20skill%20check%2C%20input%20dialog%2C%20etc...)

ox config for 3.0 ox_lib

---

ox.cfg

fix ox_lib convars

---

server.cfg

illenium-appearance locale config

---

qbox.sql

feat(sql): Required tables for illenium-appearance

---

server.cfg

tweak(cfg): groups

---

qbox.yaml

This fixes not downloading permissions.cfg

download permissions.cfg

---

qbox.sql
qbox.yaml

Added to the core with https://github.com/Qbox-project/qbx-core/pull/119

chore(recipe): remove multichar

---

qbox.yaml

feat: add qbx_idcard

---

server.cfg

Adds all the missing convars currently inside of qbx_core and adds a small description letting the user know what does what

feat(cfg): Add missing core convars with description

---

qbox.yaml

Replaces qb-weathersync 🤢 with Renewed-Weathersync 😎

replace(weathersync): Replace with Renewed-Weathersync

---

qbox-lean.yaml

fix(Weathersync): Update lean recipe to use Renewed-Weathersync

---

qbox.yaml

Update npwd version

---

qbox.yaml

Updates the NPWD version from v1.8.7 to the newest, v3.0.0

chore: update npwd to v3

---

qbox-lean.yaml
qbox.yaml
server.cfg

Needs to get merged when this is done and released:
- Qbox-Project/qbx_core#281

feat: use in-house queue

---

qbox-lean.yaml
qbox.yaml
server.cfg

- Updates NPWD from 3.0.0 to 3.8.1 and adds the new convar for built-in framework support
- Updated qbx_management to use the latest release

chore: update npwd and qbx_management

---

qbox-lean.yaml

fix(qbox-lean): management download

---

qbox-lean.yaml
qbox.yaml

Add qbx_seatbelt

---

server.cfg

Update to latest dlc

---

qbox.sql

Blocked awaiting core v1.7.0 release

feat(sql): v1.7.0 core update

---

server.cfg

Add jobs and gangs convar

---

qbox.yaml

adds missing qbx resource which will be needed once [my PR](https://github.com/Qbox-project/qbx_adminmenu/pull/48) passes through

feat: added qbx_vehicles

---

qbox.sql

Updates the table structure for house_plants in the recipe to reflect SQL changes made in qbx_weed repo

chore: update house_plants SQL table structure

---

qbox.sql

this will fix the vehicle_financing doesn't exist

updated sql to fix vehicle_financing not found

---

qbox.sql

Added qbx_bankrobbery sql regarding #21 qbx_bankrobbery pull request

feat: qbx_bankrobbery sql

---

ox.cfg

Added ox:userLocales convar

---

qbox.sql

Fixes issue with new properties table

fix(qbox.sql): use correct collation for properties

---

qbox-lean.yaml
qbox.yaml

We have removed all dependencies on PolyZone and qbx_lockpick is unused across both recipes. This removes them from the yaml downloads

feat: remove unused repos

---

qbox-lean.yaml
qbox-stable.yaml
qbox.yaml

- Changed all recipes to download release
- Added to stable recipe

feat: qbx_garages release

---

qbox.yaml

qbx_interior isn't used by the recipe any more.

feat(qbox): remove qbx_interior

---

qbox-lean.yaml
qbox-stable.yaml
qbox.yaml
server.cfg

Replaces [`qbx_loading`](https://github.com/Qbox-project/qbx_loading) with [`D4isDAVID/loadscreen`](https://github.com/D4isDAVID/loadscreen).

feat: replace loadscreen

---

ox.cfg

Needed for ox_inventory bridge. Blocked on https://github.com/Qbox-project/qbx_core/pull/528 and https://github.com/overextended/ox_inventory/pull/1763

feat(ox): qbx native bridge

---

qbox-lean.yaml
qbox.yaml

The repository was renamed, so rename it in the recipes as well.

fix: rename `qbx_policejob` to `qbx_police`

---

qbox-lean.yaml
qbox-stable.yaml
qbox.yaml

feat: mana_audio

---

server.cfg

- Add the missing `allowMethodOverrides` and `disableOverrideWarning` convars
- Standardize the use of camelCase for convars

feat(server.cfg): add missing convars

---

server.cfg

According to the [Renewed-Banking README](https://github.com/Renewed-Scripts/Renewed-Weathersync?tab=readme-ov-file#removing-compatability-files)
- [ x ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ x ] My pull request fits the contribution guidelines & code conventions.

refactor: disabled unnecessary compatability files

---

server.cfg

Small tweaks that were bothering me
- [ n/a ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ x ] My pull request fits the contribution guidelines & code conventions.

chore: small tweaks for consistency

---

ox.cfg

- Updated ox.cfg to be more readable and organized.
- Added all ox convars (lib, target, inventory) with default values.
- Small tweaks
- [ x ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ x ] My pull request fits the contribution guidelines & code conventions.

chore: organized and updated ox.cfg to include all ox convars

---

qbox-stable.yaml

Adds qbx_hud, qbx_spawn, and qbx_adminmenu to the stable recipe.

feat: add hud, spawn, and adminmenu

---

qbox-lean.yaml
qbox-stable.yaml
qbox.yaml

Adds customs to all recipes and adds spawn to lean recipe. Also updates newly added resources to use their latest release.

feat: adds spawn and customs

---

qbox-lean.yaml
qbox-stable.yaml
qbox.yaml

- Add `qbx_density` to the stable recipe
- Fix `qbx_density` downloading in main and lean reciples
- Remove unnecessary comments for replacement resources

fix(recipes): qbx_density

---

server.cfg

Not sure why we instruct people to add it instead of it just already being there but this adds it.

feat(server.cfg): acknowledge convar in cfg by default

---

server.cfg

Bumps the gamebuild back to 3258

feat(server.cfg): gamebuild to 3258

---

qbox-lean.yaml
qbox.yaml

Bump ox_fuel version to latest in qbox stable and lean

feat: bump ox_fuel version to latest

---

misc.cfg

Added new convar `sv_showBusySpinnerOnLoadingScreen`

Busy Spinner hiding

---

server.cfg

i think this organization is more useful

Move chat config for better organization + introduce new chat convars

---

items.lua

Fix for `beer` and `sandwich` label

Fix for `beer` and `sandwich` label
