Qbox-project/txAdminRecipe

server.cfg

Ensure ox_lib ~~& ox_target~~ before qb-core so that they can be used as dependencies.
Fixes Qbox-project/qb-core#18

fix(server.cfg): ensure ox_lib before qb-core

---

ox.cfg

- Adding the mats which appear by default in QBCore for mechanic currency and crafting.

feat(ox.cfg): add mechanic mats

---

qbox.yaml

When MugShotBase64 is pulled into the repo, the LICENSE.md and README.md files are placed into the [standalone] directory because MugShotBase64's resources are located in a subdirectory in the remote repo. 
This PR will download the sub-path and individually download the license and readme to keep it consistent with other resources and meet MIT license requirements of distributing the original author's license with the software.
**Previous structure:**
**After PR:**
_**Recipe has been tested**_

fix(recipe/mugshot): Extract from sub-path, re-add LICENSE.MD/README.md

---

qbox.yaml

Adds the Renewed-Weathersync properly, qbx_binoculars, qbx_carwash, and qbx_fireworks

fix: weathersync, carwash, fireworks, and binoculars

---

qbox.yaml

Users were reporting issues with deploying using [qbox.yaml](https://github.com/Qbox-project/txAdminRecipe/blob/main/qbox.yaml)
I believe this is the correct fix, but wholly untested.

fix: Fix management updates

---

permissions.cfg

Not sure why these weren't added before
https://overextended.dev/ox_lib#config

fix(config/permissions): adds missing ox_lib permissions

---

qbox-lean.yaml
qbox.yaml

When using `releases/download/latest/npwd.zip`, it downloads version `v1.8.2` instead of the actual latest version which is causing people to have issues upon downloading the recipe. I've just gone ahead and put the latest stable version in and we can then update this as we see fit.

fix(npwd): correct version

---

qbox.sql

Apparently default sql collation is utf8mb4_general_ci. This forces all tables we create to this collation
Fixes SQL collation weirdness

fix(sql): force unicode collation

---

qbox-lean.yaml
qbox.yaml

Revert to [ox_lib v1.4.0](https://github.com/overextended/ox_fuel/releases/tag/v1.4.0) since the main branch [uses recently added natives](https://github.com/overextended/ox_fuel/commit/616aa4b3c236849d86b7995f751fa4a5b57230d5) that only work on FiveM builds 8201+.

fix: use ox_fuel v1.4.0

---

qbox-stable.yaml

Fixes #58 
Haven't tested this recipe. According to the txAdmin guidelines, wasting time is only needed once every 25-50 downloads https://github.com/tabarra/txAdmin-recipes. It would be good to do more research into what GitHub expects though to optimize. Is it more waiting at smaller intervals?
This recipe also might not work yet as I put in things like npwd garages which is released, whereas qbx_garages is not.
Right now this recipe is only valuable to those who want to use as many qbox resources as possible, but will still require lots of customization as the number of released qbox resources is currently sparse

feat: add stable recipe

---

server.cfg

This enables the `loadscreen:externalShutdown` convar, which lets the loadscreen know to not shutdown automatically, since qbx_core can shut it down by itself.
This lets the loading screen run until the multicharacter menu.

feat(server.cfg): enable `loadscreen:externalShutdown`

---

server.cfg

basic-gamemode causes the bridge scene to appear. Our provided loading screen supports external shutdown and prevents this from popping up leading to a more seamless experience.

feat(server.cfg): stop basic-gamemode

---

qbox.sql

CitizenID is a generated field that has a charset of A-Z 0-9. Forcing this to a certain collation is counterintuitive as it doesn't support unicode characters. The issue that was supposed to be resolved by this is for the `name` field being unpopulated due to players with unicode characters in their name within the fivem client. This corrects that issue as well as streamlining qb-core users migrating to qbx_core.

fix(sql): enforce collation on name column

---

qbox.sql

Renewed-Banking v2.1 automatically builds the society accounts making this insert unneeded as it will be created on first start.

fix(sql): remove unneeded job account inserts

---

qbox-lean.yaml
qbox-stable.yaml
qbox.yaml
server.cfg

Use `chat` from FiveM's built-in [`system-resources`](https://github.com/citizenfx/fivem/tree/0776d79840adc87a90786a4ad9ad9b12dacb8886/ext/system-resources) to abide by the newest txAdmin [recipe guidelines](https://github.com/tabarra/txAdmin-recipes/commit/2b8b6bbd88e69aed443cef2b934a279079f3d7bf).
Tested fine with Lean recipe.

refactor: use chat from fivem system resources

---

qbox-lean.yaml
qbox-stable.yaml
qbox.yaml

Replaces qbx_vehiclefailure and qbx_prison with [QuantumMalice/vehiclehandler](https://github.com/QuantumMalice/vehiclehandler) and [xT-Development/xt-prison](https://github.com/xT-Development/xt-prison) respectively. Additionally adds these to the stable release.

refactor: replace prison and vehiclefailure

---

qbox.sql

When creating a fresh server, qbx_weed sql isn't imported by default and error "Table 'qboxproject_e321e5.weed_plants' doesn't exist" is being thrown inside server console.

fix: add SQL for qbx_weed

---

server.cfg

Defaulting to false as enabling it requires updating scripts which delete player vehicles to use the exports.qbx_core:DeleteVehicle to work correctly.

chore(cfg): add qbx:enableVehiclePersistence convar

---

server.cfg

Reverts the server's default game build to 3095 as per txAdmin's [recipe guidelines](https://github.com/tabarra/txAdmin-recipes?tab=readme-ov-file#recipe-making-guidelines-and-best-practices):
> Set the game build to the same in the CFX Default recipes

refactor(server.cfg): revert to game build 3095

---

server.cfg

Removed sv_experimentalNetGameEventHandler convar as this is no longer required in newer FXServer builds
According to the FiveM code, this change was reverted:
https://github.com/citizenfx/fivem/commit/4d8d2f696de64414b430324d072300c5b18f1f97
My pull request removes a console variable in the server.cfg file

Removed convar from server.cfg

---

items.lua
qbox-lean.yaml
qbox-stable.yaml
qbox.yaml

Created to keep compat as directed in https://github.com/Qbox-project/qbx_core/pull/614

feat: default items

---

server.cfg

Apparently this is [true by default](https://github.com/citizenfx/fivem/blob/37b6ac991a114088e744cf900cc711dc655b95ff/code/components/citizen-server-impl/src/ServerResources.cpp#L417). I don't know where I got false from. Also recommend to be used by txAdmin [here](https://github.com/tabarra/txAdmin/blob/8cbc767aa24e614fe2dc801810cb3ea58df282fd/resource/menu/server/sv_webpipe.lua#L25). So we don't wanna ship new servers with this set to false.

tweak: sv_enableNetEventReassembly default value

---

items.lua

- We currently have an item in qbx_ambulancejob/qbx_medical which uses the bandage item and this conflicts with that.

fix(items): conflicts with qbx_medical

---

server.cfg
voice.cfg

Seems like semicolons on comments are considered as end of comment/line which tries to execute the next word as a command

fix(cfg): remove semicolon from comments

---

server.cfg

That is for statistics purposes, don't want unconfigured servers impacting stats.

tweak: changed default locale to root-AQ

---

qbox-lean.yaml
qbox-stable.yaml
qbox.yaml

Simply swaps out the archived Overextended (Ox) repositories with the actively maintained Community Ox (Cox) repositories

refactor: replace ox with cox

---

qbox-lean.yaml
qbox-stable.yaml

Includes misc.cfg to both Lean & Stable recipes
(_associated warning on a fresh deploy:_  `[cmd] No such config file: misc.cfg`)

feat(recipe): include misc.cfg in lean and stable recipes

---

qbox-lean.yaml
qbox-stable.yaml
qbox.yaml

Screenshot basic is old, outdated and insecure, screencapture has a bridge for screenshot-basic while being faster, more optimised and genuinely maintained, there is no point of having 2 capture resources inside of qbox (especially when there is a bridge :) )
- [x ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x ] My pull request fits the contribution guidelines & code conventions.

Remove screenshot-basic as it isn't needed
